# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require 'bundler'
Bundler.setup(:test)

require 'rspec'
require 'mocha'
require 'bourne'

require File.expand_path('../../lib/hieroglyph', __FILE__)

Dir["./spec/support/**/*.rb"].each {|f| require f}

RSpec.configure do |config|
  # config.treat_symbols_as_metadata_keys_with_true_values = true
  # config.run_all_when_everything_filtered = true
  # config.filter_run :focus
  config.mock_with :mocha
end
